name: Build and GH-Page Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
          target-folder: dist

      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          src_path: /index.html
          dst_branch: gh-pages
          dst_repo_name: TowerDefence
          dst_owner: JosephAbbey
          username: JosephAbbey
          email: joseph@abbey1.org.uk
